services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Budapest
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /home/homelab/docker/qbitorrent/config:/config
      - /mnt/Downloads:/downloads
    ports:
      - 8090:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
