services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3005:3000
    volumes:
      - /home/homelab/docker/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
