services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    ports:
      - "8888:80"
    user: "${UID}:${GID}"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    volumes:
      - /home/homelab/docker/pgadmin:/var/lib/pgadmin
    networks:
      - database
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /home/homelab/docker/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - database

networks:
  database:
    name: database
