version: "3"
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "8585:80/tcp"
    environment:
      TZ: 'Europe/Budapest'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    volumes:
      - '/home/homelab/docker/pihole/etc-pihole:/etc/pihole'
      - '/home/homelab/docker/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
#    cap_add:
#      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped