version: '3'
services:
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Budapest
    volumes:
      - /home/homelab/docker/media/radarr/config:/config
      - /mnt/storage:/data
    restart: unless-stopped
    networks:
      - media
      - nginx
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr
    ports:
      - "8989:8989"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Budapest
    volumes:
      - /home/homelab/docker/media/sonarr/config:/config
      - /mnt/storage:/data
    restart: unless-stopped
    networks:
      - media
      - nginx
  jellyfin:
    container_name: jellyfin
    image: ghcr.io/hotio/jellyfin
    ports:
      - "8096:8096"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Budapest
    volumes:
      - /home/homelab/docker/media/jellyfin/config:/config
      - /mnt/storage:/data
    restart: unless-stopped
    networks:
      - media
      - nginx
  jackett:
    container_name: jackett
    image: ghcr.io/hotio/jackett
    ports:
      - "9117:9117"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Budapest
    volumes:
      - /home/homelab/docker/media/jackett/config:/config
    restart: unless-stopped
    networks:
      - media
      - nginx
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
      - WEBUI_PORT=8060
    volumes:
      - /home/homelab/docker/media/qbitorrent/config:/config
      - /mnt/storage:/downloads
    ports:
      - "8060:8060"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped
    networks:
      - media
      - nginx

networks:
  media:
    name: media
  nginx:
    external: true