version: '3'
services:
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Budapest
    volumes:
      - /home/homelab/docker/media/radarr/config:/config
      - /mnt/media:/data
    restart: unless-stopped
    networks:
      - media
      - nginx
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr
    ports:
      - "8989:8989"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Europe/Budapest
    volumes:
      - /home/homelab/docker/media/sonarr/config:/config
      - /mnt/media:/data
    restart: unless-stopped
    networks:
      - media
      - nginx
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /home/homelab/docker/media/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - media
      - nginx
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Budapest
    volumes:
      - /home/homelab/docker/bazarr/config:/config
      - /mnt/media/Movies:/movies #optional
      - /mnt/media/Series:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - media
      - nginx

networks:
  media:
    name: media
  nginx:
    external: true