services:
  radarr:
    container_name: radarr
    image: ghcr.io/hotio/radarr
    ports:
      - "7878:7878"
    environment:
      - PUID=0
      - PGID=0
      - UMASK=002
      - TZ=Europe/Budapest
    volumes:
      - /home/homelab/docker/media/radarr/config:/config
      - /mnt/hdd/media:/data
      - /mnt/hdd/downloads:/downloads
    restart: unless-stopped
    networks:
      - media
      - nginx
  sonarr:
    container_name: sonarr
    image: ghcr.io/hotio/sonarr
    ports:
      - "8989:8989"
    environment:
      - PUID=0
      - PGID=0
      - UMASK=002
      - TZ=Europe/Budapest
    volumes:
      - /home/homelab/docker/media/sonarr/config:/config
      - /mnt/hdd/media:/data
      - /mnt/hdd/downloads:/downloads
    restart: unless-stopped
    networks:
      - media
      - nginx
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
    volumes:
      - /home/homelab/docker/media/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - media
      - nginx
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Budapest
    volumes:
      - /home/homelab/docker/bazarr/config:/config
      - /mnt/hdd/media/movies:/movies #optional
      - /mnt/hdd/media/series:/tv #optional
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - media
      - nginx
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Budapest
    volumes:
      - /home/homelab/media/jellyfin:/config
      - /mnt/hdd/media/movies:/data/Movies
      - /mnt/hdd/media/series:/data/Series
      - /mnt/hdd/media/kids:/data/Kids
    ports:
      - 8096:8096
    restart: unless-stopped

networks:
  media:
    name: media
  nginx:
    external: true